### ISSUE TITLE
BeforeTestRun tag not executing with multiple project in single solution

### ISSUE THREAD

**Issue by Archit-Jindal** [SpecFlowOSS/SpecFlow.VisualStudio#207]
### Used Visual Studio

Visual Studio 2019

### Are the latest Visual Studio updates installed?

Yes

### SpecFlow Section in app.config or content of specflow.json

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{47BA4404-C1D3-49FA-BB5A-F513CDA20BAB}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>MBV.Foundation.customer.Testing</RootNamespace>
    <AssemblyName>MBV.Foundation.customer.Testing</AssemblyName>
    <TargetFrameworkVersion>v4.7.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <ProjectTypeGuids>{3AC096D0-A1C2-E12C-1390-A8335801FDAB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">15.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
    <ReferencePath>$(ProgramFiles)\Common Files\microsoft shared\VSTT\$(VisualStudioVersion)\UITestExtensionPackages</ReferencePath>
    <IsCodedUITest>False</IsCodedUITest>
    <TestProjectType>UnitTest</TestProjectType>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <PackageReference Include="AutoItX.Dotnet">
      <Version>3.3.14.5</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp">
      <Version>4.7.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.Infrastructure" Version="1.0.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.1.1" />
    <PackageReference Include="NUnit">
      <Version>3.12.0</Version>
    </PackageReference>
    <PackageReference Include="BoDi">
      <Version>1.4.1</Version>
    </PackageReference>
    <PackageReference Include="Cucumber.Messages">
      <Version>6.0.1</Version>
    </PackageReference>
    <PackageReference Include="DnsClient">
      <Version>1.0.7</Version>
    </PackageReference>
    <PackageReference Include="ExcelDataReader">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="ExcelDataReader.DataSet">
      <Version>3.6.0</Version>
    </PackageReference>
    <PackageReference Include="ExtentReports">
      <Version>3.1.3</Version>
    </PackageReference>
    <PackageReference Include="Gherkin">
      <Version>25.0.2</Version>
    </PackageReference>
    <PackageReference Include="Google.Protobuf">
      <Version>3.7.0</Version>
    </PackageReference>
    <PackageReference Include="HtmlAgilityPack">
      <Version>1.4.9.5</Version>
    </PackageReference>
    <PackageReference Include="HtmlAgilityPack">
      <Version>1.4.9.5</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNet.Razor">
      <Version>3.0.0</Version>
    </PackageReference>
    <PackageReference Include="MongoDB.Bson">
      <Version>2.7.2</Version>
    </PackageReference>
    <PackageReference Include="MongoDB.Driver">
      <Version>2.7.2</Version>
    </PackageReference>
    <PackageReference Include="MongoDB.Driver.Core">
      <Version>2.7.2</Version>
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter">
      <Version>2.1.0</Version>
    </PackageReference>
    <PackageReference Include="MSTest.TestFramework">
      <Version>2.1.0</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>12.0.1</Version>
    </PackageReference>
    <PackageReference Include="NUnit.Console">
      <Version>3.11.1</Version>
    </PackageReference>
    <PackageReference Include="NUnit.ConsoleRunner">
      <Version>3.11.1</Version>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter">
      <Version>3.16.1</Version>
    </PackageReference>
    <PackageReference Include="RestSharp">
      <Version>106.11.4</Version>
    </PackageReference>
    <PackageReference Include="Selenium.Support">
      <Version>3.141.0</Version>
    </PackageReference>
    <PackageReference Include="Selenium.WebDriver">
      <Version>3.141.0</Version>
    </PackageReference>
    <PackageReference Include="Selenium.WebDriver.ChromeDriver">
      <Version>104.0.5112.7900</Version>
    </PackageReference>
    <PackageReference Include="Selenium.WebDriver.GeckoDriver">
      <Version>0.26.0.1</Version>
    </PackageReference>
    <PackageReference Include="Selenium.WebDriver.IEDriver">
      <Version>3.150.1</Version>
    </PackageReference>
    <PackageReference Include="SpecFlow">
      <Version>3.3.30</Version>
    </PackageReference>
    <PackageReference Include="SpecFlow.NUnit">
      <Version>3.3.30</Version>
    </PackageReference>
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation">
      <Version>3.3.30</Version>
    </PackageReference>
    <PackageReference Include="System.Buffers">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.IO">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Net.Http">
      <Version>4.3.4</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Emit">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Emit.Lightweight">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation">
      <Version>4.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Algorithms">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Encoding">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.X509Certificates">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="System.Threading.Tasks.Extensions">
      <Version>4.4.0</Version>
    </PackageReference>
    <PackageReference Include="System.ValueTuple">
      <Version>4.4.0</Version>
    </PackageReference>
    <PackageReference Include="Utf8Json">
      <Version>1.3.7</Version>
    </PackageReference>
    <PackageReference Include="RazorEngine">
      <Version>3.9.0</Version>
    </PackageReference>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Constants.cs" />
    <Compile Include="Features\CustomerAccount.feature.cs" />
    <Compile Include="Features\CustomerLandingPage.feature.cs" />
    <Compile Include="Features\ProductDetailsPage.feature.cs" />
    <Compile Include="Features\ProductListingPage.feature.cs" />
    <Compile Include="GeneralHooks\Generic.cs" />
    <Compile Include="Pageobjects\AddVehiclePage.cs" />
    <Compile Include="Pageobjects\BasePage.cs" />
    <Compile Include="Pageobjects\CustomerAccountLoginPage.cs" />
    <Compile Include="Pageobjects\CustomerAccountPage.cs" />
    <Compile Include="Pageobjects\CustomerLandingPage.cs" />
    <Compile Include="Pageobjects\LoginPage.cs" />
    <Compile Include="Pageobjects\CookiesModelPage.cs" />
    <Compile Include="Pageobjects\ProductDetailsPage.cs" />
    <Compile Include="Pageobjects\ProductListingPage.cs" />
    <Compile Include="Pageobjects\StockDetailsPage.cs" />
    <Compile Include="Pageobjects\VehicleDetails.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Steps\Credentials.Steps.cs" />
    <Compile Include="Steps\CustomerAccountLoginPageSteps.cs" />
    <Compile Include="Steps\CustomerAccountPageSteps.cs" />
    <Compile Include="Steps\CustomerLandingPageSteps.cs" />
    <Compile Include="Steps\ProductDetailsPageSteps.cs" />
    <Compile Include="Steps\ProductListingPageSteps.cs" />
    <Compile Include="Utilitis\ExcelReader\ExcelReaderUtility.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Model\" />
    <Folder Include="Reports\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Configurations\Environment.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </None>
    <None Include="App.config" />
    <None Include="DataSheet\CustomerAccountLogin.xlsx" />
    <None Include="DataSheet\SingleAddUsed.xlsx" />
    <None Include="DataSheet\StockManagement.xlsx" />
    <None Include="DataSheet\VehicleDetails.xlsx" />
    <None Include="Features\CustomerAccount.feature" />
    <None Include="Features\CustomerLandingPage.feature" />
    <None Include="Features\ProductDetailsPage.feature" />
    <None Include="Features\ProductListingPage.feature" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Accounts\code\MBV.Foundation.Accounts.csproj">
      <Project>{3087EEDF-0173-4D9E-B5F4-BA42D8F31F7E}</Project>
      <Name>MBV.Foundation.Accounts</Name>
    </ProjectReference>
    <ProjectReference Include="..\api\MBV.Foundation.api.Testing.csproj">
      <Project>{1644e893-9f94-4398-837b-381f95cf40da}</Project>
      <Name>MBV.Foundation.api.Testing</Name>
    </ProjectReference>
    <ProjectReference Include="..\ecom\MBV.Foundation.ecom.Testing.csproj">
      <Project>{80366ec9-5928-44b0-b80d-cc38bc13033d}</Project>
      <Name>MBV.Foundation.ecom.Testing</Name>
    </ProjectReference>
    <ProjectReference Include="..\specflow\MBV.Foundation.Specflow.Testing.csproj">
      <Project>{b8c307f7-d49b-475f-857f-30f63948f90c}</Project>
      <Name>MBV.Foundation.Specflow.Testing</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="MBV.Foundation.customer.Testing.sln" />
  </ItemGroup>
  <Import Project="$(VSToolsPath)\TeamTest\Microsoft.TestTools.targets" Condition="Exists('$(VSToolsPath)\TeamTest\Microsoft.TestTools.targets')" />
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>

### Issue Description

when I use [BeforeTestRun], the method is not even called during run in CI in teamcity. While this is working fine in debugging. I'm using hook file. I searched here for solution in many questions. Also I'm using multiple projects in single solution. Each project has its own hook file.

using AventStack.ExtentReports;
using AventStack.ExtentReports.Gherkin.Model;
using AventStack.ExtentReports.Reporter;
using BoDi;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Reflection;
using TechTalk.SpecFlow;

namespace MBV.Foundation.ecom.Testing.GeneralHooks
{
    [Binding]
    public class Generic
    { 
        private static ScenarioContext _scenarioContext;
        private static ExtentReports _extentReports;
        private static ExtentHtmlReporter _extentHtmlReporter;
        private static ExtentTest _feature;
        private static ExtentTest _scenario;
        private readonly IObjectContainer _objectContainer;
        private IWebDriver driver;

        public Generic(IObjectContainer objectContainer)
        {
            _objectContainer = objectContainer;
        }

        [BeforeTestRun]
        public static void BeforeTestRun()
        {
            _extentHtmlReporter = new ExtentHtmlReporter(String.Format(Constants.DataSheets.TestingOnlyReports, $"{Environment.UserName}_{System.DateTime.Now.ToString("yyyyMMddHHmmss")}"));
            _extentHtmlReporter.Configuration().Theme = AventStack.ExtentReports.Reporter.Configuration.Theme.Dark;
            _extentReports = new ExtentReports();
            _extentReports.AttachReporter(_extentHtmlReporter);
            //_extentHtmlReporter.LoadConfig(Constants.DataSheets.XmlPath);
        }

        [BeforeFeature]
        public static void BeforeFeatureStart(FeatureContext featureContext)
        {
            if (null != featureContext)
            {
                _feature = _extentReports.CreateTest<Feature>(featureContext.FeatureInfo.Title, featureContext.FeatureInfo.Description);
            }
        }

        [BeforeScenario]
        public void BeforeScenarioStart(ScenarioContext scenarioContext)
        {
            //var browser = TestContext.Parameters.Get("BrowserType");
            var browser = ConfigurationManager.AppSettings["BrowserType"];
            SelectBrowser(browser);

            if (null != scenarioContext)
            {
                _scenarioContext = scenarioContext;
                _scenario = _feature.CreateNode<Scenario>(scenarioContext.ScenarioInfo.Title, scenarioContext.ScenarioInfo.Description);
            }

        }

        [AfterStep]
        public void AfterEachStep()
        {

            ScenarioBlock scenarioBlock = _scenarioContext.CurrentScenarioBlock;

            switch (scenarioBlock)
            {
                case ScenarioBlock.Given:
                    CreateNode<Given>();
                    break;

                case ScenarioBlock.When:
                    CreateNode<When>();
                    break;

                case ScenarioBlock.Then:
                    CreateNode<Then>();
                    break;

                default:
                    CreateNode<And>();
                    break;
            }

        }

        public void CreateNode<T>() where T : IGherkinFormatterModel
        {
            Console.WriteLine(_scenarioContext.ScenarioExecutionStatus.ToString());
            if (_scenarioContext.ScenarioExecutionStatus.ToString() == "TestSkipped")
            {
                _scenario.CreateNode<T>(_scenarioContext.StepContext.StepInfo.Text).Skip("Step Definition Pending");
            }
            else if (_scenarioContext.TestError != null)
            {
                _scenario.CreateNode<T>(_scenarioContext.StepContext.StepInfo.Text).Fail(_scenarioContext.TestError.Message);
                //_feature.AddScreenCaptureFromPath(Directory.GetParent(Assembly.GetExecutingAssembly().Location).Parent.Parent.FullName + "\\Reports\\pic.jpg").Fail(_scenarioContext.TestError.Message, MediaEntityBuilder.CreateScreenCaptureFromPath(".\\" + Directory.GetParent(Assembly.GetExecutingAssembly().Location).Parent.Parent.FullName + "\\Reports\\pic.jpg").Build());
            }
            else
            {
                _scenario.CreateNode<T>(_scenarioContext.StepContext.StepInfo.Text);
            }

        }

        [AfterScenario]
        public void CleanUp()
        {
            driver.Quit();
            _objectContainer.Dispose();
        }

        [AfterTestRun]
        public static void TearDownReport()
        {           
            _extentReports.Flush();
        }

        public void SelectBrowser(String browserType)
        {
            switch (browserType)
            {
                case "Chrome":
                    DesiredCapabilities caps = new DesiredCapabilities();
                    ChromeOptions options = new ChromeOptions();
                    options.AddArguments(
                        "start-maximized",
                        "enable-automation",
                        "--no-sandbox", //this is the relevant other arguments came from solving other issues
                        "--disable-infobars",
                        "--disable-dev-shm-usage",
                        "--disable-browser-side-navigation",
                        "--disable-gpu",
                        "--ignore-certificate-errors");
                    Dictionary<string, object> prefs = new Dictionary<string, object>();
                    prefs.Add("profile.default_content_settings.geolocation", 1);
                    caps.SetCapability(ChromeOptions.Capability, prefs);
                    driver = new ChromeDriver(options);
                    _objectContainer.RegisterInstanceAs<IWebDriver>(driver);
                    driver.Manage().Window.Maximize();
                    break;
                default:
                    throw new NotSupportedException($"{browserType} is not a supported browser");

            }

        }
    }

    }

### Steps to Reproduce

Due to above [BeforeTestRun] not executing, I'm getting error in [BeforeFeatureStart] for '_extentReports' variable is null. Because this is being initialized in [BeforeTestRun] as per above hook file.

**Comment by Archit-Jindal** [comment]
I'm getting below error message during execution from team server.
[14:48:08 ](http://13.40.98.229:90/buildConfiguration/DsltExperienceCommerce_MbvTestAutomation/14164?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&showLog=14164_2582_2582&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true&logView=flowAware)    MBV.Foundation.customer.Testing.Features.ProductListingPageFeature.MIRUKMVE_T3019_2TheUserDeletesTheirCookiesOnValueMyVehicleForm
[14:48:08 ](http://13.40.98.229:90/buildConfiguration/DsltExperienceCommerce_MbvTestAutomation/14164?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&showLog=14164_2583_2583&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true&logView=flowAware)      System.NullReferenceException : Object reference not set to an instance of an object.
[14:48:08 ](http://13.40.98.229:90/buildConfiguration/DsltExperienceCommerce_MbvTestAutomation/14164?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&showLog=14164_2584_2584&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true&logView=flowAware)         at MBV.Foundation.customer.Testing.GeneralHooks.Generic.BeforeFeatureStart(FeatureContext featureContext) in C:\BuildAgent\work\79c82bdb2de10fc1\src\Foundation\Testing\customer\GeneralHooks\Generic.cs:line 55
         at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration) in D:\a\1\s\TechTalk.SpecFlow\Bindings\BindingInvoker.cs:line 69
         at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.InvokeHook(IBindingInvoker invoker, IHookBinding hookBinding, HookType hookType) in D:\a\1\s\TechTalk.SpecFlow\Infrastructure\TestExecutionEngine.cs:line 352
         at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType) in D:\a\1\s\TechTalk.SpecFlow\Infrastructure\TestExecutionEngine.cs:line 338
         at MBV.Foundation.customer.Testing.Features.ProductListingPageFeature.FeatureSetup()

**Comment by JeroMiya** [comment]
I was experiencing this issue as well, but I found the reason was that I was incorrectly referencing SpecFlow.NUnit.Runners in a class library in the solution that I referenced from the actual test project. I fixed the issue by ONLY referencing the core SpecFlow package in the class library, and only referencing SpecFlow.NUnit.Runners from the actual test project. Issue cleared up after that and BeforeTestRun/AfterTestRun worked as expected. I have multiple test projects in my solution as well and they're all working now.

I'm not sure if this is the same issue others are experiencing, but hopefully this helps.
