### ISSUE TITLE
[DevExE2E][NET8] The numbers are uncolorful in Calculator.feature.cs file, and System.IO.FileNotFoundException throw in Output- SpecFlow.

### ISSUE THREAD

**Issue by v-hozha1** [SpecFlowOSS/SpecFlow.VisualStudio#213]
### Used Visual Studio

Visual Studio 2019

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

Actual Results:
The numbers “50, 70…” are uncolorful in Calculator.feature.cs file, and System.IO.FileNotFoundException throw in Output- SpecFlow.
![image](https://user-images.githubusercontent.com/100275240/229726926-38014661-01f7-4400-ad2f-22b02aa277bf.png)

Expected Results:
No error and waring show in Error Lists/Outputs. 
![image](https://user-images.githubusercontent.com/100275240/229727939-e9482c88-33da-4d5b-8b56-dad6cf853fe6.png)

### Steps to Reproduce

**Note:** This issue doesn’t repro if we update tfm from .NET6.0 to .NET7.0.
We use the latest VS 2022 build. But there's no option in above "Used Visual Studio" dropdown list. 

Affected Branch: Rel.d/17.6
Affected Build: Version 17.6.0 Preview 3.0 [33603.287.d17.6] + dotnet-sdk-8.0.100-preview.3.23178.7
Affected Product Language:
Affected Build link: [Pipelines - Run rel.d17.6-33603.287 (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7572652&view=ms.vss-build-web.run-extensions-tab) + [Pipelines - Run 20230329.2-8.0.100-preview.3.23178.7-172219 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2146816&view=artifacts&pathAsName=false&type=publishedArtifacts) +feeds: https://pkgs.dev.azure.com/dnceng/public/_packaging/8.0.100-preview.3.23178.7-shipping/nuget/v3/index.json

Pre-steps:
1.	Navigate to "Extensions -> Manage Extensions ->Online" and search for "SpecFlow" in the search bar.
2.	Hit Download. You'll need to restart VS for the installation to completed.
 
Steps:
1.	Create a  new project -> search and select "SpecFlow Project"
1.	On Create a new SpecFlow Project page->  Framework: .NET6.0-> Test Framework: "MSTest "-> check "Add FluentAssertions library" -> click "Create"
2.	Go to project properties page, update tfm from .NET6.0 to .NET8.0.
3.	Build the project.
4.	Double click AddTwoNumbers test in TE window -> check Calculator.feature.cs file

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-hozha1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/v-hozha1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-hozha1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><span style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:
minor-latin'>--Error List:<o:p></o:p></span></p>

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Warning |   | The project bindings (e.g. step definitions) could not   be discovered. Navigation, step completion and other features are disabled. |   |   | 0 |  

<p class=MsoNormal><span style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:
minor-latin'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='mso-bidi-font-family:Calibri;mso-bidi-theme-font:minor-latin'>-Logs:<br>
</span><span style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;
mso-font-kerning:0pt'>Info: OnActivityStarted: Starting Visual Studio
Extension...<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Info: CreateProjectScope: Initializing project: SpecFlowProject4<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Info: OnSettingsInitialized: Project settings initialized:
.NETCoreApp,Version=v8.0,SpecFlow:3.9.40<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Warning: AndDiscoveryProviderSucceed: Error during binding discovery. <o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Command executed:<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'> 
</span>C:\Users\v-hozha1\source\repos\SpecFlowProject4\SpecFlowProject4\bin\Debug\net8.0&gt;
C:\Program Files\dotnet\dotnet.exe exec C:\Users\v-hozha1\AppData\Local\Microsoft\VisualStudio\17.0_00079088\Extensions\rvnmzffg.q20\Connectors\Generic-net7.0\specflow-vs.dll
discovery
C:\Users\v-hozha1\source\repos\SpecFlowProject4\SpecFlowProject4\bin\Debug\net8.0\SpecFlowProject4.dll
&quot;&quot;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Exit code: 4<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Message: <o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>System.IO.FileNotFoundException: Could not load file or assembly
'System.Runtime, Version=8.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken,
IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32
methodInstCount)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32
methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1
methodInstantiationContext)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[]
typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
System.RuntimeType.GetMethodBase(RuntimeModule scope, Int32 typeMetadataToken)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
System.Reflection.RuntimeCustomAttributeData..ctor(RuntimeModule scope,
MetadataToken caCtorToken, ConstArray&amp; blob)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(RuntimeModule
module, Int32 tkTarget)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
SpecFlowConnector.ReflectionExecutor.Execute(DiscoveryOptions options, Func`3
testAssemblyFactory, ILogger _log, IAnalyticsContainer analytics) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\ReflectionExecutor.cs:line
15<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
SpecFlowConnector.Runner.ExecuteDiscovery(DiscoveryOptions options, Func`3
testAssemblyFactory) in
D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line
50<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
SpecFlowConnector.Runner.&lt;&gt;c__DisplayClass4_0.&lt;Run&gt;b__0(ConnectorOptions
options) in
D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line
30<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
FunctionalExtensions.Map[TSource,TResult](TSource this, Func`2 fn) in
D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\NetExtensions\FunctionalExtensions.cs:line
5<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
SpecFlowConnector.Runner.Run(String[] args, Func`3 testAssemblyFactory) in
D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\Runner.cs:line
26<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Newtonsoft.Json.JsonReaderException: Unexpected character encountered
while parsing value: D. Path '', line 0, position 0.<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
Newtonsoft.Json.JsonTextReader.ParseValue()<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at Newtonsoft.Json.JsonReader.ReadForType(JsonContract
contract, Boolean hasConverter)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader
reader, Type objectType, Boolean checkAdditionalContent)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
objectType)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type,
JsonSerializerSettings settings)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at
Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,
JsonSerializerSettings settings)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>   </span>at SpecFlow.VisualStudio.Connectors.OutProcSpecFlowConnector.Deserialize(RunProcessResult
result, Func`2 formatErrorMessage)<o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'>Warning: AndDiscoveryProviderSucceed: The project bindings (e.g. step
definitions) could not be discovered. Navigation, step completion and other
features are disabled. <o:p></o:p></span></p>

<p class=MsoNormal style='mso-layout-grid-align:none;text-autospace:none'><span
style='font-size:9.5pt;font-family:"Cascadia Mono";color:black;mso-font-kerning:
0pt'><span style='mso-spacerun:yes'>  </span>Please check the error message
above and report to <a href="https://github.com/SpecFlowOSS/SpecFlow.VS/issues">https://github.com/SpecFlowOSS/SpecFlow.VS/issues</a>
if you cannot fix.<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</body>

</html>

**Comment by Tum4ik** [comment]
I have the same problem on .NET 8

**Comment by v-hozha1** [comment]
The same issue also repro on .NET9.0.
![image](https://github.com/user-attachments/assets/7333e9a6-57dc-4c48-b502-8898af2e5611)

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1 methodInstantiationContext)
   at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.RuntimeType.GetMethodBase(RuntimeModule scope, Int32 typeMetadataToken)
   at System.Reflection.RuntimeCustomAttributeData..ctor(RuntimeModule scope, MetadataToken caCtorToken, ConstArray& blob)
   at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
   at SpecFlowConnector.ReflectionExecutor.Execute(DiscoveryOptions options, Func`3 testAssemblyFactory, ILogger _log, IAnalyticsContainer analytics) in D:\a\1\s\Connectors\SpecFlow.VisualStudio.SpecFlowConnector.Generic\ReflectionExecutor.cs:line 15
   at SpecFlowConnector.Runner.ExecuteDiscovery(DiscoveryOptions options, Func`3 testAssemblyFactory) in D:\a\1\s\Con
